# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tri-County RFC
email: akofke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The home page for the Tri-County Tridents, a social rugby club
  based in Lockport, NY.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tricountyrugby.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  akofke

# Build settings
markdown: kramdown
